"""empty message

Revision ID: 74479d5326bc
Revises: bd05bfb5b4ea
Create Date: 2024-10-18 11:54:05.062436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '74479d5326bc'
down_revision: Union[str, None] = 'bd05bfb5b4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('address', sa.String(length=256), nullable=False),
                    sa.Column('city', sa.String(length=256), nullable=False),
                    sa.Column('phone', sa.String(length=15), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_cinemas_created_at'), 'cinemas', ['created_at'], unique=False)
    op.create_index(op.f('ix_cinemas_id'), 'cinemas', ['id'], unique=False)
    op.create_table('payments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('users',
                    sa.Column('username', sa.String(length=16), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('full_name', sa.String(length=256), nullable=False),
                    sa.Column('hashed_password', sa.String(length=64), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('halls',
                    sa.Column('cinema_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('capacity', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['cinema_id'], ['cinemas.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_halls_created_at'), 'halls', ['created_at'], unique=False)
    op.create_index(op.f('ix_halls_id'), 'halls', ['id'], unique=False)
    op.create_table('screenings',
                    sa.Column('movie_id', sa.Integer(), nullable=False),
                    sa.Column('hall_id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=False),
                    sa.Column('end_time', sa.DateTime(), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
                    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_screenings_created_at'), 'screenings', ['created_at'], unique=False)
    op.create_index(op.f('ix_screenings_id'), 'screenings', ['id'], unique=False)
    op.create_table('seats',
                    sa.Column('hall_id', sa.Integer(), nullable=False),
                    sa.Column('seat_number', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['hall_id'], ['halls.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_seats_created_at'), 'seats', ['created_at'], unique=False)
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.create_table('tickets',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('screening_id', sa.Integer(), nullable=False),
                    sa.Column('seat_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='ticketstatus'), nullable=False),
                    sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
                    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.add_column('movies', sa.Column('rental_start_date', sa.Date(), nullable=False))
    op.add_column('movies', sa.Column('rental_end_date', sa.Date(), nullable=False))
    op.drop_column('movies', 'release_start_date')
    op.drop_column('movies', 'release_end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('movies', sa.Column('release_start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('movies', 'rental_end_date')
    op.drop_column('movies', 'rental_start_date')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.drop_index(op.f('ix_seats_created_at'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_screenings_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_created_at'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index(op.f('ix_halls_id'), table_name='halls')
    op.drop_index(op.f('ix_halls_created_at'), table_name='halls')
    op.drop_table('halls')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_cinemas_id'), table_name='cinemas')
    op.drop_index(op.f('ix_cinemas_created_at'), table_name='cinemas')
    op.drop_table('cinemas')
    # ### end Alembic commands ###
