"""empty message

Revision ID: f56f68851503
Revises: b28d48d98af1
Create Date: 2024-10-12 10:11:47.428110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56f68851503'
down_revision: Union[str, None] = 'b28d48d98af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_start_date', sa.DateTime(), nullable=False))
    op.add_column('movies', sa.Column('release_end_date', sa.DateTime(), nullable=False))
    op.drop_column('movies', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('movies', 'release_end_date')
    op.drop_column('movies', 'release_start_date')
    # ### end Alembic commands ###
